export const DEFAULT_PARTICLE_SETTINGS = {
  particleCount: 100000,
  particleSize: 1,
  brightness: 1.5,
  exposure: 7.2,
  bloom: 0,
  bloomRadius: 0.5,
  depth: 0.6,
  yawRange: 2,
  pitchRange: 2,
  cameraDistance: 7.2,
  zoom: 1.3,
  cameraSmoothing: 0.2,
  floatAmplitude: 4,
  floatSpeed: 3,
  figureSpeed: 1.3,
  flowSpeed: 2,
  flowSpeedBias: 0.5,
  flowRange: 1,
  focus: 0.25,
  dof: 2,
  hueShift: -10,
  saturation: 1,
  galaxyRatio: 0.2,
  galaxyStrength: 0.8,
  sceneStrength: 0.45,
  subjectClarity: 1,
  contourProtection: 1,
  edgeDispersion: 2,
  introTrail: 0,
  flowTrail: 0,
  centerWhiteness: 0.85,
  mouseFieldRadius: 0.15,
  mouseFieldStrength: 2,
};

export type ParticleSettings = typeof DEFAULT_PARTICLE_SETTINGS;
